name: Windows fork build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      windows-only: true
